name: Build and Push Quarkus Native Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  build-native:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract project version
        id: get_version
        run: |
          VERSION=$(grep "^\s*version\s*=\s*" build.gradle.kts | head -n 1 | sed -E 's/\s*version\s*=\s*"(.*)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check version is not SNAPSHOT
        if: endsWith(steps.get_version.outputs.version, '-SNAPSHOT')
        run: |
          echo "Version is SNAPSHOT, skipping publish."
          exit 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun --version
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "PATH=$BUN_INSTALL/bin:$PATH" >> $GITHUB_ENV

      - name: Build Quarkus native app
        run: ./gradlew build -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false -Dquarkus.native.container-build=true -x test

      - name: Upload runner binary
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-runner
          path: build/*-runner


  download-kubectl:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare build/apps directory
        run: mkdir -p build/apps

      - name: Download kubectl
        run: |
          echo "Downloading kubectl ..."
          curl -L -o build/apps/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: Upload kubectl as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubectl
          path: build/apps/kubectl


  docker:
    runs-on: ubuntu-latest
    needs: [ build-native, download-kubectl ]
    steps:
      - uses: actions/checkout@v4

      - name: Download runner binary
        uses: actions/download-artifact@v4
        with:
          name: quarkus-runner
          path: build

      - name: Prepare build/apps directory
        run: mkdir -p build/apps

      - name: Download kubectl artifact
        uses: actions/download-artifact@v4
        with:
          name: kubectl
          path: build/apps

      - name: Verify kubectl
        run: |
          chmod +x build/apps/kubectl
          build/apps/kubectl version --client

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/main/docker/Dockerfile.native-micro
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/k7s:${{ needs.build-native.outputs.version }}
